# Generated by Django 4.2 on 2023-08-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.CharField(choices=[('child', 'child'), ('teen', 'teen'), ('adult', 'adult')], default='adult', max_length=255),
        ),
    ]
