# Generated by Django 4.2 on 2023-07-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'مخاطب', 'verbose_name_plural': 'مخاطبان'},
        ),
    ]
